import NextTopLoader from 'nextjs-toploader';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { TanstackQueryClientProvider } from '@/providers/tanstack-query';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Equipment Booking',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQueryClientProvider>
          <>
            <NextTopLoader color="#ff9000" />
            {children}
            <Toaster />
          </>
        </TanstackQueryClientProvider>
      </body>
    </html>
  );
}
