import NextTopLoader from 'nextjs-toploader';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { Navbar } from '@/components/common/navbar';
import { TanstackQueryClientProvider } from '@/providers/tanstack-query';
import { Toaster } from '@/components/ui/toaster';
import { Sidebar } from '@/components/common/sidebar';
import { getSession } from '@/actions/get-session';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Equipment Booking',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQueryClientProvider>
          <>
            <NextTopLoader color="#ff9000" />
            <div className="flex h-full w-full items-start justify-start">
              <Sidebar user={user} />
              <div className="w-full">
                <Navbar user={user} />
                {children}
                <Toaster />
              </div>
            </div>
          </>
        </TanstackQueryClientProvider>
      </body>
    </html>
  );
}
